export default defineEventHandler(() => {
  const rekomendasi = {
    harian: [
      {
        judul: "Morning Stretch",
        deskripsi: "Peregangan ringan 10 menit untuk memulai hari",
        waktu: "06:00",
        durasi: 10,
        kategori: "pemanasan",
        warna: "#f59e0b",
      },
      {
        judul: "Cardio Pagi",
        deskripsi: "Lari ringan atau jumping jack 20 menit",
        waktu: "06:30",
        durasi: 20,
        kategori: "kardio",
        warna: "#ef4444",
      },
      {
        judul: "Yoga & Meditasi",
        deskripsi: "Relaksasi dan fokus mental sebelum bekerja",
        waktu: "07:00",
        durasi: 30,
        kategori: "yoga",
        warna: "#8b5cf6",
      },
      {
        judul: "Push Up Sore",
        deskripsi: "3 set push up, sit up, dan squat",
        waktu: "17:00",
        durasi: 15,
        kategori: "kekuatan",
        warna: "#6366f1",
      },
      {
        judul: "Jalan Malam",
        deskripsi: "Jalan santai 20-30 menit setelah makan malam",
        waktu: "20:00",
        durasi: 25,
        kategori: "kardio",
        warna: "#06b6d4",
      },
    ],
    mingguan: [
      {
        judul: "Senin – Full Body Workout",
        deskripsi: "Latihan keseluruhan tubuh: chest, back, legs, core",
        hari: "Senin",
        waktu: "06:00",
        durasi: 60,
        kategori: "kekuatan",
        warna: "#6366f1",
      },
      {
        judul: "Selasa – Lari 5K",
        deskripsi: "Lari pagi target 5 kilometer tanpa berhenti",
        hari: "Selasa",
        waktu: "05:30",
        durasi: 45,
        kategori: "kardio",
        warna: "#ef4444",
      },
      {
        judul: "Rabu – Upper Body",
        deskripsi: "Fokus dada, bahu, trisep, dan bisep",
        hari: "Rabu",
        waktu: "06:00",
        durasi: 50,
        kategori: "kekuatan",
        warna: "#f59e0b",
      },
      {
        judul: "Kamis – Yoga & Recovery",
        deskripsi: "Pemulihan aktif dengan yoga dan stretching",
        hari: "Kamis",
        waktu: "07:00",
        durasi: 45,
        kategori: "yoga",
        warna: "#8b5cf6",
      },
      {
        judul: "Jumat – Lower Body",
        deskripsi: "Squat, lunges, deadlift, dan calf raise",
        hari: "Jumat",
        waktu: "06:00",
        durasi: 55,
        kategori: "kekuatan",
        warna: "#10b981",
      },
      {
        judul: "Sabtu – HIIT Training",
        deskripsi: "High intensity interval training 30 menit",
        hari: "Sabtu",
        waktu: "07:00",
        durasi: 30,
        kategori: "hiit",
        warna: "#f97316",
      },
      {
        judul: "Minggu – Istirahat Aktif",
        deskripsi: "Jalan santai, renang, atau bersepeda ringan",
        hari: "Minggu",
        waktu: "08:00",
        durasi: 60,
        kategori: "recovery",
        warna: "#06b6d4",
      },
    ],
    bulanan: [
      {
        judul: "Minggu 1 – Foundation",
        deskripsi: "Bangun kebiasaan dasar: cardio 3x, kekuatan 2x seminggu",
        durasi: 45,
        kategori: "rencana",
        warna: "#6366f1",
      },
      {
        judul: "Minggu 2 – Intensitas Naik",
        deskripsi: "Tambah durasi cardio, tingkatkan beban latihan kekuatan",
        durasi: 60,
        kategori: "rencana",
        warna: "#8b5cf6",
      },
      {
        judul: "Minggu 3 – Peak Training",
        deskripsi: "Puncak intensitas: 5x latihan, fokus pada performa",
        durasi: 75,
        kategori: "rencana",
        warna: "#ef4444",
      },
      {
        judul: "Minggu 4 – Deload & Evaluasi",
        deskripsi: "Turunkan intensitas, evaluasi progres, persiapan bulan berikutnya",
        durasi: 30,
        kategori: "recovery",
        warna: "#10b981",
      },
    ],
  };

  return rekomendasi;
});
